{% set name = "nng" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nanomsg/nng/archive/v{{ version }}.tar.gz
  sha256: 50b7264bd8f0901f7ebdf3ec7c48f4e23dd689bbe7b2917d9d8fad58ffd09e5c
  patches:
    - test.patch  # [linux]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
    - mbedtls >=3.5
  run:
    - ucrt  # [win]
    - {{ pin_compatible('mbedtls', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/lib/libnng.so  # [linux]
    - test -f $PREFIX/lib/libnng.dylib  # [osx]
    - nngcat -V  # [unix]
    - nngcat.exe -V  # [win]

about:
  home: https://nng.nanomsg.org/
  summary: 'nanomsg-next-generation -- light-weight brokerless messaging'
  description: |
    nanomsg-next-generation -- light-weight brokerless messaging
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://nng.nanomsg.org/man/
  dev_url: https://github.com/nanomsg/nng

extra:
  recipe-maintainers:
    - jan-janssen
    - carlodri
