{% set name = "nng" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nanomsg/nng/archive/v{{ version }}.tar.gz
  sha256: 40e6af7bdd5d02ee98ba8fe5fd5c149ce3e5a555f202cdc837e3ead2d7cc7534
  patches:
    - test.patch  # [linux]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
    - mbedtls  # [not win]
  run:
    - ucrt  # [win]
    - mbedtls  # [not win]

test:
  commands:
    - test -f $PREFIX/lib/libnng.so  # [linux]
    - test -f $PREFIX/lib/libnng.dylib  # [osx]
    - nngcat -V  # [unix]
    - nngcat.exe -V  # [win]

about:
  home: https://nng.nanomsg.org/
  summary: 'nanomsg-next-generation -- light-weight brokerless messaging'
  description: |
    nanomsg-next-generation -- light-weight brokerless messaging
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://nng.nanomsg.org/man/
  dev_url: https://github.com/nanomsg/nng

extra:
  recipe-maintainers:
    - jan-janssen
    - carlodri
