{% set name = "nng" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nanomsg/nng/archive/v{{ version }}.tar.gz
  sha256: 035f2c3cad4e45fc0d978c54a338c197d1937527ae6feb82180d428a96b83474
  patches:
    - test.patch  # [linux]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
    - mbedtls >=3.5
  run:
    - ucrt  # [win]
    - {{ pin_compatible('mbedtls', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/lib/libnng.so  # [linux]
    - test -f $PREFIX/lib/libnng.dylib  # [osx]
    - nngcat -V  # [unix]
    - nngcat.exe -V  # [win]

about:
  home: https://nng.nanomsg.org/
  summary: 'nanomsg-next-generation -- light-weight brokerless messaging'
  description: |
    nanomsg-next-generation -- light-weight brokerless messaging
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://nng.nanomsg.org/man/
  dev_url: https://github.com/nanomsg/nng

extra:
  recipe-maintainers:
    - jan-janssen
    - carlodri
